name: Documentation generation CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout myBranch
      - uses: actions/checkout@v2

      # generate the C++ doxygen files
      - name: Doxygen Action C++
        uses: rr-mark/doxygen-action@v1.3.1
        with:
          working-directory: '.'
          doxyfile-path: 'internal/doc/Doxyfile'

      # store the doc files
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: internal/doc
          retention-days: 1

  copy:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      # checkout the gh-pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # download the doc files, most of which are generated above
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: internal/doc

      # add, commit and push to gh-pages
      - name: Commit changes
        uses: rr-mark/add-and-commit@v7
        with:
          author_name: Mark Johnson
          author_email: mark@rivelinrobotics.com
          message: 'Update docs'
          branch: gh-pages
          add: '["internal/doc/html/*"]'
