name: Generate and deploy documentation
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Checkout master branch.
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
      
      # Install Graphviz and Doxygen.
      - name: Install Graphviz and Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo apt-get install doxygen
      
      # Run Doxygen.
      - name: Run Doxygen
        run: |
          cd repository
          doxygen internal/doc/Doxyfile

      # Store the documentation files.
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: repository/internal/doc
          retention-days: 1

  copy:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      # Checkout target repository.
      - uses: actions/checkout@v2
        with:
          repository: rr-mark/target
          path: target

      # download the documentation files.
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: target/internal/doc
      
      # Commit and push changes.
      - name: Commit and push changes
        run:
          cd target
          git add internal/doc/*
          git commit -m "Automatically updated documentation."
          git push origin master
