name: 'Deploy Doxygen documentation to GitHub Pages'

on:
  push:
    branches: [ master ]


jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./internal/doc/Doxyfile"
        working-directory: "."
    
    - name: Debug1
      run: |
        ls ${{ github.workspace }}
        
    - name: Debug2
      run: |
        ls ${{ github.workspace }}/internal/doc
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "./internal/doc/html"
