name: Generate and deploy documentation
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Checkout master branch.
      - uses: actions/checkout@v2

      # Run doxygen to generate documentation files.
      # Uses an unmodified fork of mattnotmitt/doxygen-action.
      # (Forked for security reasons.)
      - name: Doxygen Action C++
        uses: rr-mark/doxygen-action@v1.3.1
        with:
          working-directory: '.'
          doxyfile-path: 'internal/doc/Doxyfile'

      # Store the documentation files.
      - name: Upload Output Directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: internal/doc
          retention-days: 1

  copy:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      # Checkout gh-pages-doc branch.
      - uses: actions/checkout@v2
        with:
          ref: gh-pages-doc

      # download the documentation files.
      - name: Download Output Directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: internal/doc

      # Add, commit and push to gh-pages-doc.
      # Uses an unmodified fork of EndBug/add-and-commit.
      # (Forked for security reasons.)
      - name: Commit changes
        uses: rr-mark/add-and-commit@v7
        with:
          author_name: Mark Johnson
          author_email: mark@rivelinrobotics.com
          message: 'Update docs'
          branch: gh-pages-doc
          add: '["internal/doc/html/*"]'
