name: 'Deploy Doxygen documentation to GitHub Pages'

on:
  push:
    branches: [ master ]


jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    
    permissions:
      actions: [ read, write ]
      checks: [ read, write ]
      contents: [ read, write ]
      deployments: [ read, write ]
      id-token: [ read, write ]
      issues: [ read, write ]
      packages: [ read, write ]
      pages: [ read, write ]
      pull-requests: [ read, write ]
      repository-projects: [ read, write ]
      security-events: [ read, write ]
      statuses: [ read, write ]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./internal/doc/Doxyfile"
        working-directory: "."
    
    - name: Debug1
      run: |
        ls ${{ github.workspace }}
        
    - name: Debug2
      run: |
        ls ${{ github.workspace }}/internal/doc
        
    - name: Debug3
      run: |
        ls ${{ github.workspace }}/internal/doc/html
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "./internal/doc/html"
